### ISSUE TITLE
ValueError: Expected collection name 

### ISSUE THREAD

**Issue by boral** [sime2408/scrapalot-chat#5]
Got this error:

`ValueError: Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got db`

Was using this document : [https://github.com/imartinez/privateGPT/blob/main/source_documents/state_of_the_union.txt](https://github.com/imartinez/privateGPT/blob/main/source_documents/state_of_the_union.txt)

**Comment by sime2408** [comment]
This project is designed to have **sub-folders** in the source_documents, thus following the architecture of having multiple separate databases. So in my case everything works fine:

```shell
/usr/local/anaconda3/envs/scrapalot-chat/bin/python scrapalot_ingest.py 
Select an option or 'q' to quit:

1. Select an existing directory
2. Create a new directory
3. Use current ingest_source_directory: ./source_documents/physics

Enter your choice ("q" for quit): 2
Enter the name for the new directory: test
Created new directory: ./source_documents/test
Place your source material into the new folder and press enter to continue...
Creating new vectorstore from ./source_documents/test
Loading documents from ./source_documents/test
Loading new documents: 100%|██████████████████████| 1/1 [00:04<00:00,  4.15s/it]

./source_documents/test/state_of_the_union.txt 
Loaded 1 new documents from ./source_documents/test
Split into 43 chunks of text (max. 1000 tokens each)
Ingestion complete! You can now run scrapalot_main.py to query your documents

Process finished with exit code 0
```
