### ISSUE TITLE
Unclear Readme - gpu doesn't work on my setup

### ISSUE THREAD

**Issue by StephenDWright** [sime2408/scrapalot-chat#6]
Great project but is there a disconnect between the current state of the project and the readme? For example, the readme references .env settings that are not in the file, which is fine, but have the settings been deprecated. I am unclear about n_threads. It is referenced in the readme, the code actually auto detects the number of threads as far as I can see, the template .env omits it, and when I run the script CUDA is working, BLAS is set to 1, but only 512MB of Vram is engaged and no layers are offloaded to the gpu. 

That being said, it is such a great project. Many of the requests made in other similar projects are actually implemented here.

**Comment by sime2408** [comment]
If you're referring to `GPU_MODEL_N_THREADS` that's removed from the example.env since it defaults to 16 threads, you're free to set it to something more but for GPU that's actually irrelevant since GPU can spawn 1000 virtual threads if it's capable of it. It's just a problem with `LlamaCpp` class that accepts this field for CPU, and I added some fake defaults for GPU. A more important property of GPU is :

```python
n_gpu_layers=gpu_is_enabled if calculate_layer_count() else None,
```

where I did some calculations, so maybe I did some bug there? I will delete `GPU_MODEL_N_THREADS` from the readme file. 

If no layers are offloaded to the GPU that means that your `llama-cpp-python` is not installed correctly. Since this project begs for contributors you're free to test it in your system and propose a solution for Linux 🙏🏻 , because I didn't test Linux very well. I am on Windows and macOS.

**Comment by StephenDWright** [comment]
> If you're referring to `GPU_MODEL_N_THREADS` that's removed from the example.env since it defaults to 16 threads, you're free to set it to something more but for GPU that's actually irrelevant since GPU can spawn 1000 virtual threads if it's capable of it. It's just a problem with `LlamaCpp` class that accepts this field for CPU, and I added some fake defaults for GPU. A more important property of GPU is :
> 
> ```python
> n_gpu_layers=gpu_is_enabled if calculate_layer_count() else None,
> ```
> 
> where I did some calculations, so maybe I did some bug there? I will delete `GPU_MODEL_N_THREADS` from the readme file.
> 
> If no layers are offloaded to the GPU that means that your `llama-cpp-python` is not installed correctly. Since this project begs for contributors you're free to test it in your system and propose a solution for Linux 🙏🏻 , because I didn't test Linux very well. I am on Windows and macOS.

Thanks for the response. I am also on windows. When running the app, the following is displayed:

ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060
llama.cpp: loading model from models/wizard-vicuna-13B.ggmlv3.q5_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 8 (mostly Q5_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 10583.26 MB (+ 1608.00 MB per state)
llama_model_load_internal: offloading 0 layers to GPU
llama_model_load_internal: total VRAM used: 512 MB
....................................................................................................
llama_init_from_file: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 

This leads me to believe that llama-cpp-python was installed correctly but I can try to remove it and reinstall. I've gotten it to work with other similar projects will continue to work on it and see if there is an issue with my environment.

**Comment by sime2408** [comment]
Take a look at the section in `README.md` `"GPU (Windows)"`. If nothing works for you try the section mentioning the following text: If the above doesn't work for you, you must manually build the `llama-cpp-python` library with CMake.

This means you have to uninstall `pip3 uninstall llama-cpp-python` and install the version which you built using:
`cmake -G "Visual Studio 16 2019" -A x64 -D CUDAToolkit_ROOT="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8" ..`

That version has to have `set(LLAMA_CUBLAS 1)`. Sometimes Windows won't pick up these env variables for God knows which reason. Linux setup (as it's reported to me) works fine, no need to do magic like on Windows, cause it's just a stupid OS for such a thing.

Also, pay attention to your NVIDIA CUDA Toolkit ([download 11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local), don't download 12) and drivers for Visual Studio

**Comment by StephenDWright** [comment]
> Take a look at the section in `README.md` `"GPU (Windows)"`. If nothing works for you try the section mentioning the following text: If the above doesn't work for you, you must manually build the `llama-cpp-python` library with [CMake](https://cmake.org/download/).
> 
> This means you have to uninstall `pip3 uninstall llama-cpp-python` and install the version which you built using: `cmake -G "Visual Studio 16 2019" -A x64 -D CUDAToolkit_ROOT="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8" ..`
> 
> That version has to have `set(LLAMA_CUBLAS 1)`. Sometimes Windows won't pick up these env variables for God knows which reason. Linux setup (as it's reported to me) works fine, no need to do magic like on Windows, cause it's just a stupid OS for such a thing.
> 
> Also, pay attention to your NVIDIA CUDA Toolkit ([download 11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local), don't download 12) and drivers for Visual Studio. Do not have multiple CUDA toolkits installed.
> 
> By the way, can you debug what this method from my code returns to you?
> 
> ```python
> def is_cuda_available() -> bool:
>     if torch.cuda.is_available():
>         return True
>     else:
>         return False
> ```

It returns True.

**Comment by StephenDWright** [comment]
@sime2408 I found the issue. Even though I added GPU_IS_ENABLED = true to the .env, it is not being read. I manually set the number of n_gpu_layers to 32 and it successfully offloaded the 32 layers to the gpu.

**Comment by sime2408** [comment]
closing this as I found a bug. Instead of:

`n_gpu_layers=gpu_is_enabled if calculate_layer_count() else None,`

fixed this by:

`n_gpu_layers=calculate_layer_count() if gpu_is_enabled else None,`
