### ISSUE TITLE
High CPU usage even though GPU is being used

### ISSUE THREAD

**Issue by StephenDWright** [sime2408/scrapalot-chat#8]
I pulled the latest version and encountered the following. 
Issue: Extremely high CPU usage with some GPU usage. Ingest still works file. The high CPU usage occurs after submitting a question and is first slower when generating batches and then answering the question. I would naturally assume that it is using the CPU somehow instead of the GPU but it shows that layers were successfully offloaded to the GPU. 

This is the output: 

gml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060
llama.cpp: loading model from models/Wizard-Vicuna-7B-Uncensored.ggmlv3.q6_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 4096
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 18 (mostly Q6_K)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 1997.16 MB (+ 1026.00 MB per state)
llama_model_load_internal: allocating batch_size x 1 MB = 512 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloaded 32/35 layers to GPU
llama_model_load_internal: total VRAM used: 5580 MB
...................................................................................................
llama_init_from_file: kv self size  = 2048.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 
Existing directories in ./source_documents:

 1. TTUTA

Enter the index number of the database, or more separated by comma (q for quit): 1 

Storing env variable defaults: ./db/TTUTA

Enter question (q for quit): What is sick leave?
2023-06-19 14:35:54,511 INFO     Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2023-06-19 14:35:55,106 INFO     Successfully imported ClickHouse Connect C data optimizations
2023-06-19 14:35:55,116 INFO     Using python library for writing JSON byte strings
2023-06-19 14:35:55,206 INFO     loaded in 450 embeddings
2023-06-19 14:35:55,208 INFO     loaded in 1 collections
2023-06-19 14:35:55,211 INFO     collection with name TTUTA already exists, returning existing collection

Seeking for answer from: [TTUTA]. May take some minutes...
Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.14s/it]

Previously worked without issue.

**Comment by sime2408** [comment]
Try to manipulate with 7B models and these properties, which you can lower down, best model is `MODEL_TYPE=llamacpp `and `MODEL_ID_OR_PATH=models/WizardLM-7B-uncensored.ggmlv3.q8_0.bin` (for my CPU testing):

```ini
INGEST_TARGET_SOURCE_CHUNKS=6
MODEL_N_CTX=4096
MODEL_N_BATCH=1024
MODEL_ANSWER_N_WORDS=200
```

CPU threads are calculated 80% of max, so this code, I guess I should externalize this percentage to an env property:

```python
# Number of CPU cores
n_cpu = multiprocessing.cpu_count()

# Now, if you want to use, say, 80% of your CPU cores:
cpu_model_n_threads = int(0.8 * n_cpu)
```

**Comment by sime2408** [comment]
I suppose you manage to solve this, closing
